# [Can a default module in a Google App Engine app be a sibling of a non-default module in terms of folder structure?](http://stackoverflow.com/q/34110178)
runtime: nodejs
env: flex
service: default

manual_scaling:
  instances: 1